### ISSUE TITLE
Invoicing for EU institutions - No VAT required

### ISSUE THREAD

**Issue by SebastianrodpeEU** [fortrabbit/help#51]
Hello, I work at the European Parliament and we are considering using Fortrrabit as the domain hosting of a new website. 

We are based in Belgium but we have VAT-exemption treatment by EU law. Therefore, our invoice would need to be issued without VAT. Can you please confirm you can issue a invoice without VAT for us?

You **do not have to do any paperwork for us**. All the paper work will be handle by us. 

Once you have issued the invoice without VAT, we will provide your accounting team with a document in English and German that you can present to the German tax authorities. I attached a template of the document in English and German. (NB: You do not have to do anything to fill out this paper, it will all be handled by us. )

[151 DE.docx](https://github.com/fortrabbit/help/files/5942769/151.DE.docx)
[151 EN.docx](https://github.com/fortrabbit/help/files/5942770/151.EN.docx)

Thank you,
Sebastian

Please feel free to call me at:
+32 496 89 72 99

**Comment by ostark** [comment]
I replied in the support chat.
